# Generated by Django 4.0.3 on 2022-04-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxarid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='buyer_account',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='buyer_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='buyer_inn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='buyer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='buyer_rayon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='buyer_region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='lot_date_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='lot_dateini',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='lot_group',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='lot_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='lot_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='lot_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='seller_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='seller_inn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='seller_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='seller_rayon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='seller_region',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
